### ISSUE TITLE
Subterm node

### ISSUE THREAD

**Issue by atlv24** [unda-ml/unda#27]
add an operation type to ensure that a computation is already present in the compute graph. useful for referencing intermediate derivatives generated by autodiff with peace of mind that no additional work is created. remove these nodes if the constraint is satisified during common term extraction, and error if they are still present when compiling to XLA

**Comment by Ebanflo42** [comment]
Is this for debugging? I somewhat see the motivation but I would not create an extra operation node for this. As it stands, all node operations carry an XLA meaning and are expected to be present.

**Comment by Ebanflo42** [comment]
I vote to close this
