### ISSUE TITLE
Printed AST parsing

### ISSUE THREAD

**Issue by atlv24** [unda-ml/unda#32]
reverse Context::to_string using nom and strum. This will enable save/load and easier unit testing.

short term we should probably do this via serde and save out the whole context for simplicity.

**Comment by Ebanflo42** [comment]
I'm not sure I see the motivation behind this? What is gained over just calling all the operations using the context functions?

**Comment by Ebanflo42** [comment]
I would move to close this as I think it will be better for interoperability to save StableHLO strings
